package btclient

const (
	DEFAULT_WALLET_ACCOUNT        = ""
	EMPTY_STR                     = ""
	UNSPENT_MINIMUM_CONFIRMATIONS = 2
	UNSPENT_MAXIMUM_CONFIRMATIONS = 9999999

	UNKNOWN_TRANX_INDEX   int   = -1
	UNKNOWN_BLOCK_HEIGHT  int64 = -1
	UNKNOWN_CONFIRMATIONS int64 = -1
)
